// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6Id1jy3YRvSgxzYbCgzlHuCo4LReaig',
    appId: '1:7258596606:web:f9babe5bc15eae5bbeb1af',
    messagingSenderId: '7258596606',
    projectId: 'gate-keeper-ca928',
    authDomain: 'gate-keeper-ca928.firebaseapp.com',
    storageBucket: 'gate-keeper-ca928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTsN8Sj96FVPgMtetlhTDxYEIo6uKyjVc',
    appId: '1:7258596606:android:1674eab526f7910ebeb1af',
    messagingSenderId: '7258596606',
    projectId: 'gate-keeper-ca928',
    storageBucket: 'gate-keeper-ca928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS614SXQL7FcdmoRQsgQO_M9TuacQtBlI',
    appId: '1:7258596606:ios:98cf3b362ea77708beb1af',
    messagingSenderId: '7258596606',
    projectId: 'gate-keeper-ca928',
    storageBucket: 'gate-keeper-ca928.firebasestorage.app',
    iosBundleId: 'com.example.gateKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS614SXQL7FcdmoRQsgQO_M9TuacQtBlI',
    appId: '1:7258596606:ios:98cf3b362ea77708beb1af',
    messagingSenderId: '7258596606',
    projectId: 'gate-keeper-ca928',
    storageBucket: 'gate-keeper-ca928.firebasestorage.app',
    iosBundleId: 'com.example.gateKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn6Id1jy3YRvSgxzYbCgzlHuCo4LReaig',
    appId: '1:7258596606:web:6831873fce93fb31beb1af',
    messagingSenderId: '7258596606',
    projectId: 'gate-keeper-ca928',
    authDomain: 'gate-keeper-ca928.firebaseapp.com',
    storageBucket: 'gate-keeper-ca928.firebasestorage.app',
  );
}
